services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
      target: example
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=example.settings
    command: [
      "poetry",
      "run",
      "example",
    ]

  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYENV_ROOT=/opt/pyenv
    command: [
      "poetry",
      "run",
      "tests",
    ]

  tox:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYENV_ROOT=/opt/pyenv
    command: tox
