services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
      target: example
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=example.settings

  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYENV_ROOT=/opt/pyenv
    command: pytest

  tox:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYENV_ROOT=/opt/pyenv
    command: tox
