[tox]
isolated_build = true
envlist =
    py311-django52
    py312-django{52,60}
    py313-django{52,60}
    py314-django{52,60}

[testenv]
description = Run pytest against {envname}
deps =
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    pytest>=9.0.3
    pytest-cov>=7.1.0
    pytest-django>=4.12.0
    pytest-xdist>=3.8.0
    djangorestframework>=3.17.0
setenv =
    DJANGO_SETTINGS_MODULE = example.settings
    PYTHONPATH = {toxinidir}
commands =
    pytest --cov=admin_shelf --cov-report=xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy {posargs}
